apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
      - name: couchbase
        image: couchbase:community-7.2.0
        ports:
        - containerPort: 8091
        - containerPort: 8092
        - containerPort: 8093
        - containerPort: 11210
        env:
        - name: CLUSTER_NAME
          value: "ecommerce-cluster"
        volumeMounts:
        - name: couchbase-data
          mountPath: /opt/couchbase/var
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: couchbase-data
        persistentVolumeClaim:
          claimName: couchbase-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
  namespace: ecommerce
spec:
  selector:
    app: couchbase
  ports:
  - name: admin
    port: 8091
    targetPort: 8091
  - name: views
    port: 8092
    targetPort: 8092
  - name: query
    port: 8093
    targetPort: 8093
  - name: data
    port: 11210
    targetPort: 11210
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchbase-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi